Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (0,2,0,0,'I','0%','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (2,2,12,70,'A','12%','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (6,2,0,0,'I','No Objeto de Impuesto','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3011,3,0,0,'I','ICE - CIGARRILLOS RUBIOS','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3021,3,0,0,'I','ICE - CIGARRILLOS NEGROS','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3023,3,150,0,'I','ICE - PRODUCTOS DEL TABACO Y SUCEDÁNEOS DEL TABACO EXCEPTO CIGARRILLOS','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3041,3,0 ,0,'I','ICE - CERVEZA','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3072,3,5  ,0,'I','ICE - CAMIONETAS, FURGONETAS, CAMIONES Y VEHICULOS DE RESCATE CUYO PVP SEA HASTA DE 30000 USD','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3073,3,5  ,0,'I','ICE - VEHÍCULOS MOTORIZADOS CUYO PVP SEA HASTA DE 20000 USD','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3074,3,10 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS EXCEPTO CAMIONETAS Y FURGONETAS ENTRE 20000 Y 30000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3075,3,15 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS PVP ENTRE 30000 Y 40000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3077,3,20 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 40.000 HASTA 50.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3078,3,25 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 50.000 HASTA 60.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3079,3,30 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 60.000 HASTA 70.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3080,3,35 ,0,'I','ICE - VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 70.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3081,3,15 ,0,'I','ICE - AVIONES, AVIONETAS, HELICÓPTEROS, MOTOS ACUÁTICAS, TRICARES, CUADRONES, YATES Y BARCOS DE RECREO','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3051,3,10 ,0,'I','ICE - BEBIDAS GASEOSAS','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3031,3,0 ,0,'I','ICE - ALCOHOL Y PRODUCTOS ALCOHÓLICOS, DISTINTOS A LA CERVEZA','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3610,3,20 ,0,'I','ICE - PERFUMES Y AGUAS DE TOCADOR','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3620,3,35 ,0,'I','ICE - VIDEOJUEGOS','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3630,3,300,0,'I','ICE - ARMAS DE FUEGO, ARMAS DEPORTIVAS Y MUNICIONES','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3640,3,100,0,'I','ICE - FOCOS INCANDESCENTES','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3092,3,15 ,0,'I','ICE - SERVICIOS DE TELEVISIÓN PAGADA','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3650,3,35 ,0,'I','ICE - SERVICIOS DE CASINOS, SALAS DE JUEGO (BINGO - MECÁNICOS) Y OTROS JUEGOS DE AZAR','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3660,3,35 ,0,'I','ICE - CUOTAS, MEMBRESÍAS, AFLIACIONES, ACCIONES Y SIMILARES QUE COBREN A SUS MIEMBROS Y USUARIOS LOS CLUBES SOCIALES, CUYO MONTO SUPERE 1.500 USD ANUAL','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3173,3,14 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP MAYOR A USD. 40.000  HASTA USD 50.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3174,3,20 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP MAYOR A USD. 50.000  HASTA USD 60.000','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3175,3,26 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP MAYOR A USD. 60.000  HASTA USD 70.000','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3176,3,32 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP MAYOR A USD. 70.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3171,3,0 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP SEA DE HASTA USD. 35.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3172,3,8 ,0,'I','ICE - VEHÍCULOS HÍBRIDOS O ELÉCTRICOS CUYO PVP MAYOR A USD. 35.000 HASTA USD 40.000','2009-07-04',null); 
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (1,2,0,30,'R','30%','2009-07-04',null);
Insert into IMPUESTO_VALOR (CODIGO ,CODIGO_IMPUESTO,PORCENTAJE,PORCENTAJE_RETENCION,TIPO_IMPUESTO,DESCRIPCION,FECHA_INICIO,FECHA_FIN) values (3,2,0,100,'R','100%','2009-07-04',null);

INSERT INTO IMPUESTO_VALOR VALUES('303',1,10,NULL,'R','Honorarios profesionales y dietas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('304',1,8,NULL,'R','Servicios predomina el intelecto','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('307',1,2,NULL,'R','Servicios predomina la mano de obra','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('308',1,2,NULL,'R','Servicios entre sociedades','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('309',1,1,NULL,'R','Servicios publicidad y comunicación','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('310',1,1,NULL,'R','Servicio transporte privado de pasajeros o servicio público o privado de carga','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('312',1,1,NULL,'R','Transferencia de bienes muebles de naturaleza corporal','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('319',1,1,NULL,'R','Arrendamiento mercantil','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('320',1,8,NULL,'R','Arrendamiento bienes inmuebles','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('322',1,1,NULL,'R','Seguros y reaseguros (primas y cesiones)','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323',1,2,NULL,'R','Por rendimientos financieros (No aplica para IFIs)','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323A',1,2,NULL,'R','Por RF: depósitos Cta Corriente','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323B1',1,2,NULL,'R','Por RF:  depósitos Cta Ahorros Sociedades','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323B2',1,0,NULL,'R','Por RF:  depósitos Cta Ahorros Persona Natural','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323C',1,0,NULL,'R','Por rendimientos financieros:  depósitos en cuentas exentas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323D',1,2,NULL,'R','Por rendimientos financieros: compra, cancelación o redención de mini bemÂ´s y bemÂ´s','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323E',1,2,NULL,'R','Por RF: depósito a plazo','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323F',1,2,NULL,'R','Por rendimientos financieros: operaciones de reporto - repos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323G',1,2,NULL,'R','Por RF: inversiones (captaciones)','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323H',1,2,NULL,'R','Por RF: obligaciones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323I',1,2,NULL,'R','Por RF: bonos convertible en acciones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323J',1,2,NULL,'R','Por RF: bonos de organismos y gobiernos extranjeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('323K',1,2,NULL,'R','Por RF: entre IFIs','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('325',1,15,NULL,'R','Por loterías, rifas, apuestas y similares','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('327',1,0.2,NULL,'R','Por venta de combustibles a comercializadoras ','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('328',1,0.3,NULL,'R','Por venta de combustibles a distribuidores','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('332',1,0,NULL,'R','Otras compras de bienes y servicios no sujetas a retención','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('333',1,NULL,NULL,'R','Convenio de Débito o Recaudación','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('334',1,NULL,NULL,'R','Por compras con tarjeta de crédito','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('340',1,1,NULL,'R','Otras retenciones aplicables el 1%','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('341',1,2,NULL,'R','Otras retenciones aplicables el 2%','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('342',1,8,NULL,'R','Otras retenciones aplicables el 8%','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('343',1,25,NULL,'R','Otras retenciones aplicables el 25%','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('403',1,5,25,'R','Sin convenio de doble tributación intereses por financiamiento de proveedores externos ','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('405',1,5,25,'R','Sin convenio de doble tributación intereses de créditos externos ','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('421',1,25,NULL,'R','Sin convenio de doble tributación por otros conceptos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('427',1,NULL,NULL,'R','Pagos al exterior no sujetos a retención','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401',1,NULL,NULL,'R','Con convenio de doble tributación','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AA',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AB',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AC',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AD',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania- Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AE',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AF',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AG',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AH',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AI',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AJ',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AK',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AL',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania- Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AM',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AN',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401AO',1,NULL,NULL,'R','Con convenio de doble tributación: Alemania - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BA',1,NULL,NULL,'R','Con convenio de doble tributación: Argentina - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BB',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BC',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BD',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina- Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BE',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BF',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BG',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Cñnones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BH',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BI',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BK',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BL',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina- Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BM',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BN',1,NULL,NULL,'R','Con convenio de doble tributación: Argentina -  Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401BO',1,NULL,NULL,'R','Con convenio de doble tributación:  Argentina - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CA',1,NULL,NULL,'R','Con convenio de doble tributación: Bélgica - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CB',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CC',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica- Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CD',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica- Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CE',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CF',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CG',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CH',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CI',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CK',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CL',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CM',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CN',1,NULL,NULL,'R','Con convenio de doble tributación: Bélgica - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401CO',1,NULL,NULL,'R','Con convenio de doble tributación:  Bélgica - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DA',1,NULL,NULL,'R','Con convenio de doble tributación: Bolivia - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DB',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DC',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia- Navegación Marñtima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DD',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia- Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DE',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DF',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DG',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Cñnones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DH',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DI',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia- Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DK',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DL',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DM',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DN',1,NULL,NULL,'R','Con convenio de doble tributación: Bolivia - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401DO',1,NULL,NULL,'R','Con convenio de doble tributación:  Bolivia - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EA',1,NULL,NULL,'R','Con convenio de doble tributación: Brasil - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EB',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EC',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ED',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EE',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EF',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EG',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Cñnones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EH',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil- Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EI',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EK',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EL',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EM',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EN',1,NULL,NULL,'R','Con convenio de doble tributación: Brasil - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401EO',1,NULL,NULL,'R','Con convenio de doble tributación:  Brasil - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FA',1,NULL,NULL,'R','Con convenio de doble tributación: Canadñ - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FB',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FC',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Navegación Marñtima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FD',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FE',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FF',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FG',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Cánones o regalñas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FH',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá- Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FI',1,NULL,NULL,'R','Con convenio de doble tributación: Canadá - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FJ',1,NULL,NULL,'R','Con convenio de doble tributación: Canadá - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FK',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FL',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FM',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FN',1,NULL,NULL,'R','Con convenio de doble tributación: Canadá - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401FO',1,NULL,NULL,'R','Con convenio de doble tributación:  Canadá - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GA',1,NULL,NULL,'R','Con convenio de doble tributación: Chile - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GB',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GC',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Navegación Marñtima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GD',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GE',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GF',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GG',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GH',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GI',1,NULL,NULL,'R','Con convenio de doble tributación: Chile - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GJ',1,NULL,NULL,'R','Con convenio de doble tributación: Chile - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GK',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GL',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GM',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GN',1,NULL,NULL,'R','Con convenio de doble tributación: Chile - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401GO',1,NULL,NULL,'R','Con convenio de doble tributación:  Chile - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HA',1,NULL,NULL,'R','Con convenio de doble tributación: Colombia - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HB',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HC',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HD',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HE',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HF',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HG',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HH',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HI',1,NULL,NULL,'R','Con convenio de doble tributación: Colombia - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HJ',1,NULL,NULL,'R','Con convenio de doble tributación: Colombia - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HK',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HL',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HM',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HN',1,NULL,NULL,'R','Con convenio de doble tributación: Colombia - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401HO',1,NULL,NULL,'R','Con convenio de doble tributación:  Colombia - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IA',1,NULL,NULL,'R','Con convenio de doble tributación: España - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IB',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IC',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ID',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IE',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IF',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IG',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IH',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401II',1,NULL,NULL,'R','Con convenio de doble tributación: España - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IJ',1,NULL,NULL,'R','Con convenio de doble tributación: España - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IK',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IL',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IM',1,NULL,NULL,'R','Con convenio de doble tributación:  España - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IN',1,NULL,NULL,'R','Con convenio de doble tributación: España - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401IO',1,NULL,NULL,'R','Con convenio de doble tributación:  España - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JA',1,NULL,NULL,'R','Con convenio de doble tributación: Francia - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JB',1,NULL,NULL,'R','Con convenio de doble tributación:  Francia - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JC',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JD',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JE',1,NULL,NULL,'R','Con convenio de doble tributación:  Francia - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JF',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JG',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JH',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JI',1,NULL,NULL,'R','Con convenio de doble tributación:  Francia - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Francia - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JK',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JL',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JM',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JN',1,NULL,NULL,'R','Con convenio de doble tributación:  Francia - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401JO',1,NULL,NULL,'R','Con convenio de doble tributación:   Francia - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KA',1,NULL,NULL,'R','Con convenio de doble tributación: Italia - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KB',1,NULL,NULL,'R','Con convenio de doble tributación:  Italia - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KC',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KD',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KE',1,NULL,NULL,'R','Con convenio de doble tributación:  Italia - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KF',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KG',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KH',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KI',1,NULL,NULL,'R','Con convenio de doble tributación:  Italia - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Italia - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KK',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KL',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KM',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KN',1,NULL,NULL,'R','Con convenio de doble tributación:  Italia - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401KO',1,NULL,NULL,'R','Con convenio de doble tributación:   Italia - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LA',1,NULL,NULL,'R','Con convenio de doble tributación: México - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LB',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LC',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LD',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LE',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LF',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LG',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LH',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LI',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LJ',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LK',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LL',1,NULL,NULL,'R','Con convenio de doble tributación:  México - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LM',1,NULL,NULL,'R','Con convenio de doble tributación:   México - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LN',1,NULL,NULL,'R','Con convenio de doble tributación: México - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401LO',1,NULL,NULL,'R','Con convenio de doble tributación:   México - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MA',1,NULL,NULL,'R','Con convenio de doble tributación: Perú - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MB',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MC',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MD',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ME',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MF',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MG',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MH',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MI',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MK',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ML',1,NULL,NULL,'R','Con convenio de doble tributación:  Perú - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MM',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MN',1,NULL,NULL,'R','Con convenio de doble tributación: Perú - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401MO',1,NULL,NULL,'R','Con convenio de doble tributación:   Perú - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NA',1,NULL,NULL,'R','Con convenio de doble tributación: Rumania - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NB',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NC',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ND',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NE',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NF',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NG',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NH',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NI',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NK',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NL',1,NULL,NULL,'R','Con convenio de doble tributación:  Rumania - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NM',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NN',1,NULL,NULL,'R','Con convenio de doble tributación: Rumania - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401NO',1,NULL,NULL,'R','Con convenio de doble tributación:   Rumania - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OA',1,NULL,NULL,'R','Con convenio de doble tributación: Suiza - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OB',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OC',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OD',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OE',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OF',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OG',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OH',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OI',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OK',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OL',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OM',1,NULL,NULL,'R','Con convenio de doble tributación:  Suiza - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401ON',1,NULL,NULL,'R','Con convenio de doble tributación: Suiza - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401OO',1,NULL,NULL,'R','Con convenio de doble tributación:   Suiza - otros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PA',1,NULL,NULL,'R','Con convenio de doble tributación: Venezuela - Rentas Inmobiliarias','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PB',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Beneficios empresariales','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PC',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - Navegación Marítima y/o aérea','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PD',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - Empresas Asociadas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PE',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Dividendos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PF',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - Intereses','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PG',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - Cánones o regalías','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PH',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - Ganancias de capital','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PI',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Servicios profesionales independientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PJ',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Servicios profesionales dependientes','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PK',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Participación de consejeros','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PL',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Artistas y deportistas','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PM',1,NULL,NULL,'R','Con convenio de doble tributación:  Venezuela - Pensiones','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PN',1,NULL,NULL,'R','Con convenio de doble tributación: Venezuela - Reembolso de Gastos','2010-06-01',NULL);
INSERT INTO IMPUESTO_VALOR VALUES('401PO',1,NULL,NULL,'R','Con convenio de doble tributación:   Venezuela - otros','2010-06-01',NULL);
